# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod download
release:
  github:
    owner: pivotal-cf
    name: om
builds:
- env:
  - CGO_ENABLED=0
  targets:
  - darwin_amd64
  - darwin_arm64
  - linux_amd64
  - linux_arm64
  - windows_amd64
  ldflags:
  - -s -w -X "main.version={{.Version}}"
archives:
- id: github
  format: binary
  name_template: "om-{{ .Os }}-{{ .Arch }}-{{ .Version }}"
- id: homebrew
  format: "tar.gz"
  name_template: "om-{{ .Os }}-{{ .Arch }}-{{ .Version }}"
  format_overrides:
  - goos: windows
    format: zip
brews:
  - 
    ids:
    - homebrew
    test: |
      system "#{bin}/om --version"
    install:
      bin.install "om"
    repository:
      owner: pivotal-cf
      name: om
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  disable: true