name: test

on:
  push:
    branches:
    - main
    tags:
    - "*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OM
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: om

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5
 
      - name: Test
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo
          ginkgo -r -race -succinct -randomizeAllSpecs -randomizeSuites -keepGoing .
        working-directory: om
        env:
          CGO_ENABLED: 1
